
```{r}
rm(list = ls())
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
A <- read.csv(url,header = T)
pdf <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf"
download.file(pdf, destfile = "./data/codebook.pdf", mode = "wb")
# B <- pdf(file = "./data/codebook.pdf")
```

# Question 1
```{r}
library("dplyr")
# d1 <- filter(A, ACR == 3 & AGS == 6)
agricultureLogical <- ifelse(A$ACR == 3 & A$AGS == 6,T,F)
which(agricultureLogical)
```


# Question 2

```{r}

# install.packages("jpeg")
library("jpeg")
pic <- "https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg"
# z <- tempfile()
# download.file(pic,destfile = z,mode="wb")
download.file(pic,destfile = "./data/pic.jpg",mode="wb")
#pic <- readJPEG(z,native = T)
jpg <- readJPEG("./data/pic.jpg", native = T)
# file.remove(z) # cleanup
quantile(jpg,probs = c(0.3,0.8))
```


# Question 3
```{r}
GDP <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
gdp <- read.csv(GDP,header = T)
EDU <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
edu <- read.csv(EDU, header = T)
names(gdp)
names(edu)
```


```{r}
d3 <- merge(gdp,edu,by.x = "X", by.y = "CountryCode")
# str(d3)
d3$Gross.domestic.product.2012 <- as.numeric(d3$Gross.domestic.product.2012)
gdp_desc <- arrange(d3,Gross.domestic.product.2012)
#thirteen <- filter(gdp_desc, Gross.domestic.product.2012 == 13)
```


# Question 4

What is the average GDP ranking for the "High income: OECD" 
and "High income: nonOECD" group?
```{r}
library("tidyr")

nonOECD <- d3 %>% 
        filter(Income.Group == "High income: nonOECD" )
OECD <- d3 %>%
        filter(Income.Group == "High income: OECD")
d4 <- rbind(nonOECD,OECD)
d4$Gross.domestic.product.2012 <- as.numeric(d4$Gross.domestic.product.2012)

d5 <- d4 %>% separate(Income.Group,c("income","group"),": ") %>% 
        select(X,Gross.domestic.product.2012,group)%>%
        group_by(group) %>% 
        mutate(rankavg = mean(Gross.domestic.product.2012,na.rm = T))%>%
        arrange(group,Gross.domestic.product.2012)
```

# Question 5

```{r}

d3$Gross.domestic.product.2012 <- as.numeric(d3$Gross.domestic.product.2012)
#with(d3,quantile(Gross.domestic.product.2012,na.rm = T,probs = seq(0.2, 0.4, 0.6,0.8)))

d6 <- select(d3,X,Gross.domestic.product.2012, Income.Group)
d6$gdpgroup <- cut(d6$Gross.domestic.product.2012,breaks = quantile(d6$Gross.domestic.product.2012,na.rm = T,probs = c(0,0.2,0.4,0.6,0.8,1)))
xt <- with(d6,table(gdpgroup, Income.Group, useNA = "ifany"))
ftable(xt)
```



